import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
    centered: {flex: 1, justifyContent: 'center', alignItems: 'center'},
    container: {padding: 16, alignItems: 'center'},
    editButton: {flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-end', marginBottom: 16, gap: 4},
    editText: {color: '#228be6', fontSize: 13},
    title: {fontSize: 32, fontWeight: '700', marginBottom: 16, textAlign: 'center'},
    detailRow: {flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', marginBottom: 10, width: '100%', gap: 6},
    detailLabel: {fontWeight: '700', fontSize: 15},
    detailValue: {fontSize: 15, color: '#333', flex: 1},
    locationLink: {textDecorationLine: 'underline', color: '#228be6'},
    copiedLabel: {fontSize: 12, color: '#40c057'},
    rsvpRow: {flexDirection: 'row', alignItems: 'center', marginTop: 8, gap: 10},
    rsvpButton: {borderRadius: 16, paddingHorizontal: 14, paddingVertical: 6},
    rsvpButtonText: {fontWeight: '600', fontSize: 14},
    guestButton: {borderWidth: 1, borderColor: '#228be6', borderRadius: 6, paddingHorizontal: 8, paddingVertical: 4},
    guestButtonText: {color: '#228be6', fontSize: 12},
    seriesLink: {color: '#228be6', fontSize: 13, marginTop: 4},
    seriesDate: {fontSize: 15, paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#eee', color: '#333'},
    seriesDateUpcoming: {fontWeight: 'bold'},
    modalOverlay: {flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end'},
    modalContent: {backgroundColor: '#fff', borderTopLeftRadius: 16, borderTopRightRadius: 16, padding: 24},
    modalTitle: {fontSize: 18, fontWeight: '700', marginBottom: 12},
    modalBody: {fontSize: 14, color: '#555', marginBottom: 16},
    modalOption: {paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#eee'},
    modalOptionText: {fontSize: 16},
    modalButton: {
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 8,
        padding: 12,
        alignItems: 'center',
        marginBottom: 8
    },
    modalButtonPrimary: {backgroundColor: '#228be6', borderColor: '#228be6'},
    modalButtonText: {fontSize: 15, fontWeight: '600'},
    modalCancel: {textAlign: 'center', color: '#228be6', marginTop: 16, fontSize: 16},
    modalClose: {textAlign: 'center', marginTop: 16, fontSize: 15, color: '#228be6'},
    fullModalContainer: {flex: 1, padding: 20, paddingTop: 60},
    guestRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#eee'
    },
    rsvpBadge: {borderRadius: 12, paddingHorizontal: 10, paddingVertical: 4},
    rsvpBadgeText: {fontSize: 12, fontWeight: '600'},
    closeButton: {backgroundColor: '#f0f0f0', borderRadius: 8, padding: 14, alignItems: 'center', marginTop: 16},
    closeButtonText: {fontSize: 16, color: '#333'},
    seriesModalOverlay: {flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'center', paddingHorizontal: 32},
    seriesModalContent: {backgroundColor: '#fff', borderRadius: 16, padding: 24, maxHeight: '40%'},
});