import {StyleSheet} from 'react-native';
import {colors} from './colors';

export const styles = StyleSheet.create({
    centered: {flex: 1, justifyContent: 'center', alignItems: 'center'},
    container: {flex: 1, padding: 16},
    titleRow: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4},
    title: {fontSize: 25, fontWeight: '500', color: '#222'},
    description: {fontSize: 13, color: '#666', marginBottom: 8, lineHeight: 19},
    metaRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8},
    metaText: {fontSize: 12, color: '#888'},
    reminderRow: {flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 14},
    actionIcons: {flexDirection: 'row', gap: 8},
    iconButton: {
        width: 30,
        height: 30,
        borderRadius: 15,
        borderWidth: 1,
        borderColor: colors.terracotta.primary,
        justifyContent: 'center',
        alignItems: 'center'
    },
    iconButtonFilled: {
        width: 30,
        height: 30,
        borderRadius: 15,
        backgroundColor: colors.terracotta.lightFill,
        justifyContent: 'center',
        alignItems: 'center'
    },
    iconBadge: {
        position: 'absolute',
        top: -4,
        right: -4,
        backgroundColor: colors.terracotta.primary,
        borderRadius: 8,
        minWidth: 16,
        height: 16,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 3
    },
    iconBadgeText: {color: '#fff', fontSize: 10, fontWeight: '700'},
    chipRow: {marginBottom: 16, maxHeight: 44, flexGrow: 0, flexShrink: 0},
    memberChip: {
        backgroundColor: colors.terracotta.lightFill,
        borderRadius: 20,
        paddingHorizontal: 12,
        paddingVertical: 6,
        marginRight: 8
    },
    memberChipName: {fontSize: 12, fontWeight: '500', color: colors.terracotta.text},
    memberChipUsername: {fontSize: 10, color: colors.terracotta.text, opacity: 0.7},
    memberCard: {borderWidth: 1, borderColor: '#ddd', borderRadius: 8, padding: 12, marginBottom: 8},
    memberRow: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
    memberInfo: {flex: 1},
    memberActions: {flexDirection: 'row', alignItems: 'center', gap: 8},
    membersLabel: {fontWeight: '700'},
    pendingBadge: {
        backgroundColor: '#fee2e2',
        borderRadius: 4,
        paddingHorizontal: 6,
        paddingVertical: 2,
        alignSelf: 'flex-start',
        marginBottom: 4
    },
    pendingText: {color: '#ef4444', fontSize: 11, fontWeight: '600'},
    memberName: {fontSize: 15, fontWeight: '500'},
    memberUsername: {fontSize: 13, color: '#666'},
    roleRow: {flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 8},
    selectButton: {justifyContent: 'center'},
    selectButtonText: {fontSize: 13, color: colors.terracotta.primary, fontWeight: '500'},
    removeButton: {
        borderWidth: 1,
        borderColor: '#ef4444',
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 6,
        alignItems: 'center'
    },
    removeText: {color: '#ef4444', fontSize: 13},
    button: {backgroundColor: colors.sage.primary, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8},
    buttonText: {color: '#fff', fontWeight: '600', fontSize: 13},
    modalContainer: {flex: 1, padding: 20, paddingTop: 60, backgroundColor: '#fff'},
    fullScreenHeader: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16},
    modalTitle: {fontSize: 22, fontWeight: '700', marginBottom: 16},
    modalSectionLabel: {fontSize: 12, fontWeight: '600', color: '#888', marginBottom: 8, marginTop: 8},
    divider: {height: 1, backgroundColor: colors.sage.lightFill, marginVertical: 12},
    eventsList: {maxHeight: 220},
    modalEventCard: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#e9ecef',
        borderRadius: 10,
        padding: 12,
        marginBottom: 8
    },
    modalEventCardTitle: {fontSize: 14, fontWeight: '500', color: '#212529', marginBottom: 2},
    modalEventCardDate: {fontSize: 12, color: '#495057'},
    searchInput: {borderWidth: 1, borderColor: '#ccc', borderRadius: 8, padding: 10, marginBottom: 12},
    inviteRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#eee'
    },
    inviteButton: {backgroundColor: colors.terracotta.primary, borderRadius: 6, paddingHorizontal: 10, paddingVertical: 6},
    inviteButtonDisabled: {backgroundColor: '#ccc'},
    inviteButtonText: {color: '#fff', fontSize: 13},
    emptyText: {textAlign: 'center', color: '#888', marginTop: 16},
    closeButton: {backgroundColor: '#f0f0f0', borderRadius: 8, padding: 14, alignItems: 'center', marginTop: 16},
    closeButtonText: {fontSize: 16, color: '#333'},
    sectionRow: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10},
    sectionTitle: {fontSize: 16, fontWeight: '500', color: '#222'},
    eventsScroll: {flex: 1},
    eventsScrollContent: {paddingBottom: 24},
    eventCard: {
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#e9ecef',
        borderRadius: 12,
        padding: 12,
        marginBottom: 8
    },
    eventName: {fontSize: 14, fontWeight: '500', color: '#212529', marginBottom: 2},
    eventDate: {fontSize: 12, color: '#495057', marginBottom: 6},
    rsvpPill: {alignSelf: 'flex-start', borderRadius: 10, paddingHorizontal: 8, paddingVertical: 3},
    rsvpPillText: {fontSize: 11, fontWeight: '600'},
    modalOverlay: {flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end'},
    modalContent: {backgroundColor: '#fff', borderTopLeftRadius: 16, borderTopRightRadius: 16, padding: 24},
    modalOption: {paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#eee'},
    modalOptionText: {fontSize: 16},
    modalCancel: {textAlign: 'center', color: colors.terracotta.primary, marginTop: 16, fontSize: 16},
    input: {borderWidth: 1, borderColor: '#ccc', borderRadius: 8, padding: 10, fontSize: 16},
    rejectionButton: {flexDirection: 'row', gap: 8}
});
