import {StyleSheet} from 'react-native';
import {colors} from './colors';

export const styles = StyleSheet.create({
    centered: {flex: 1, justifyContent: 'center', alignItems: 'center'},
    container: {flex: 1, padding: 20, backgroundColor: '#FAF7F2'},
    titleRow: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12, marginBottom: 22},
    title: {fontSize: 24, fontWeight: '500', color: '#1a1a1a', marginBottom: 4},
    ledBy: {fontSize: 14, color: '#5c5c58'},
    notifyButton: {
        width: 42,
        height: 42,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: colors.terracotta.primary,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: 'transparent'
    },
    notifyButtonActive: {backgroundColor: colors.sage.primary, borderColor: colors.sage.primary},
    description: {fontSize: 15, color: '#1a1a1a', marginBottom: 22, lineHeight: 22},
    reminderRow: {flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 14},
    actionIcons: {flexDirection: 'row', gap: 8, alignItems: 'center'},
    iconButton: {
        width: 32,
        height: 32,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: colors.terracotta.primary,
        justifyContent: 'center',
        alignItems: 'center'
    },
    iconBadge: {
        position: 'absolute',
        top: -4,
        right: -4,
        backgroundColor: colors.terracotta.primary,
        borderRadius: 8,
        minWidth: 16,
        height: 16,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 3
    },
    iconBadgeText: {color: '#fff', fontSize: 10, fontWeight: '700'},
    chipRow: {marginBottom: 22, maxHeight: 60, flexGrow: 0, flexShrink: 0},
    memberChip: {
        backgroundColor: colors.sage.lightFill,
        borderRadius: 14,
        paddingHorizontal: 14,
        paddingVertical: 8,
        marginRight: 8,
        justifyContent: 'center'
    },
    memberChipName: {fontSize: 14, fontWeight: '500', color: colors.sage.text},
    memberChipUsername: {fontSize: 12, color: colors.sage.text, opacity: 0.75},
    memberCard: {borderWidth: 1, borderColor: '#ddd', borderRadius: 8, padding: 12, marginBottom: 8},
    memberRow: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
    memberInfo: {flex: 1},
    memberActions: {flexDirection: 'row', alignItems: 'center', gap: 8},
    sectionLabel: {fontSize: 13, color: '#8a8a86', marginBottom: 12},
    pendingBadge: {
        backgroundColor: '#fee2e2',
        borderRadius: 4,
        paddingHorizontal: 6,
        paddingVertical: 2,
        alignSelf: 'flex-start',
        marginBottom: 4
    },
    pendingText: {color: '#ef4444', fontSize: 11, fontWeight: '600'},
    memberName: {fontSize: 15, fontWeight: '500'},
    memberUsername: {fontSize: 13, color: '#666'},
    roleRow: {flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 8},
    selectButton: {justifyContent: 'center'},
    selectButtonText: {fontSize: 13, color: colors.terracotta.primary, fontWeight: '500'},
    declineButton: {
        borderWidth: 1,
        borderColor: colors.terracotta.primary,
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 6,
        alignItems: 'center'
    },
    declineText: {color: colors.terracotta.primary, fontSize: 13},
    removeButton: {
        borderWidth: 1,
        borderColor: '#d97a7a',
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 6,
        alignItems: 'center'
    },
    removeText: {color: '#d97a7a', fontSize: 13},
    button: {backgroundColor: colors.sage.primary, borderRadius: 9, paddingHorizontal: 14, paddingVertical: 9, flexDirection: 'row', alignItems: 'center', gap: 4},
    buttonText: {color: '#fff', fontWeight: '500', fontSize: 13},
    modalContainer: {flex: 1, padding: 20, paddingTop: 60, backgroundColor: '#fff'},
    fullScreenHeader: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16},
    modalTitle: {fontSize: 22, fontWeight: '700', marginBottom: 16},
    modalSectionLabel: {fontSize: 12, fontWeight: '600', color: '#888', marginBottom: 8, marginTop: 8},
    divider: {height: 1, backgroundColor: colors.sage.lightFill, marginVertical: 12},
    eventsList: {maxHeight: 220},
    modalEventCard: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#e9ecef',
        borderRadius: 10,
        padding: 12,
        marginBottom: 8
    },
    modalEventCardTitle: {fontSize: 14, fontWeight: '500', color: '#212529', marginBottom: 2},
    modalEventCardDate: {fontSize: 12, color: '#495057'},
    modalBody: {fontSize: 14, color: '#555', marginBottom: 16},
    modalButton: {
        borderWidth: 1,
        borderColor: colors.terracotta.primary,
        borderRadius: 8,
        padding: 12,
        alignItems: 'center',
        marginBottom: 8
    },
    modalButtonPrimary: {backgroundColor: colors.sage.primary, borderColor: colors.sage.primary},
    modalButtonText: {fontSize: 15, fontWeight: '600'},
    searchInput: {borderWidth: 1, borderColor: '#ccc', borderRadius: 8, padding: 10, marginBottom: 12},
    inviteRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#eee'
    },
    inviteButton: {backgroundColor: colors.terracotta.primary, borderRadius: 6, paddingHorizontal: 10, paddingVertical: 6},
    inviteButtonDisabled: {backgroundColor: '#ccc'},
    inviteButtonText: {color: '#fff', fontSize: 13},
    emptyText: {textAlign: 'center', color: '#888', marginTop: 16},
    closeButton: {backgroundColor: '#f0f0f0', borderRadius: 8, padding: 14, alignItems: 'center', marginTop: 16},
    closeButtonText: {fontSize: 16, color: '#333'},
    sectionRow: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12},
    sectionTitle: {fontSize: 16, fontWeight: '500', color: '#1a1a1a'},
    eventsScroll: {flex: 1},
    eventsScrollContent: {paddingBottom: 24},
    eventCard: {
        backgroundColor: '#fff',
        borderRadius: 14,
        padding: 16,
        marginBottom: 12
    },
    eventName: {fontSize: 16, fontWeight: '500', color: '#1a1a1a', marginBottom: 4},
    eventDate: {fontSize: 13, color: '#8a8a86', marginBottom: 10},
    rsvpPill: {alignSelf: 'flex-start', borderRadius: 16, paddingHorizontal: 14, paddingVertical: 6},
    rsvpPillText: {fontSize: 13, fontWeight: '500'},
    modalOverlay: {flex: 1, backgroundColor: 'rgba(0,0,0,0.4)', justifyContent: 'flex-end'},
    modalContent: {backgroundColor: '#fff', borderTopLeftRadius: 16, borderTopRightRadius: 16, padding: 24},
    modalOption: {paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#eee'},
    modalOptionText: {fontSize: 16},
    modalCancel: {textAlign: 'center', color: colors.terracotta.primary, marginTop: 16, fontSize: 16},
    input: {borderWidth: 1, borderColor: '#ccc', borderRadius: 8, padding: 10, fontSize: 16},
    rejectionButton: {flexDirection: 'row', gap: 8}
});
